var request = require('request'),
cheerio = require('cheerio'),
cardLinks = []
urls = [
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Yugi_(TCG-NA-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Kaiba_(TCG-NA-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Joey_(TCG-NA-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Pegasus_(TCG-NA-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Yugi_Evolution_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Kaiba_Evolution_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck_2006_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Jaden_Yuki_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Syrus_Truesdale_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Yu-Gi-Oh!_5D%27s_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Yu-Gi-Oh!_5D%27s_2009_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Duelist_Toolbox_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Dawn_of_the_Xyz_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Xyz_Symphony_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Super_Starter:_V_for_Victory_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Yugi_Reloaded_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Kaiba_Reloaded_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Super_Starter:_Space-Time_Showdown_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starter_Deck:_Yuya_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Structure_Deck:_Dragon%27s_Roar_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Structure_Deck:_Zombie_Madness_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Structure_Deck:_Blaze_of_Destruction_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Structure_Deck:_Fury_from_the_Deep_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Structure_Deck:_Warrior%27s_Triumph_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Structure_Deck:_Spellcaster%27s_Judgment_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Structure_Deck:_Invincible_Fortress_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Structure_Deck:_Lord_of_the_Storm_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Structure_Deck:_Dinosaur%27s_Rage_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Structure_Deck:_Machine_Re-Volt_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Rise_of_the_Dragon_Lords_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:The_Dark_Emperor_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Zombie_World_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Spellcaster%27s_Command_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Warriors%27_Strike_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Machina_Mayhem_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Structure_Deck:_Marik_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Dragunity_Legion_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Lost_Sanctuary_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Gates_of_the_Underworld_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Dragons_Collide_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Samurai_Warlords_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Realm_of_the_Sea_Emperor_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Onslaught_of_the_Fire_Kings_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Saga_of_Blue-Eyes_White_Dragon_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Cyber_Dragon_Revolution_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Realm_of_Light_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Geargia_Rampage_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:HERO_Strike_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Synchron_Extreme_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Master_of_Pendulum_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Emperor_of_Darkness_Structure_Deck_(TCG-EN-1E)',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Pendulum_Domination_Structure_Deck_(TCG-EN-1E)?action=edit&redlink=1',
  'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Legend_of_Blue_Eyes_White_Dragon_(TCG-NA-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Metal_Raiders_(TCG-NA-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Magic_Ruler_(TCG-NA-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Invasion_of_Chaos_(TCG-NA-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Ancient_Sanctuary_(TCG-NA-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Soul_of_the_Duelist_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Rise_of_Destiny_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Flaming_Eternity_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Pharaoh%27s_Servant_(TCG-NA-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Labyrinth_of_Nightmare_(TCG-NA-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Legacy_of_Darkness_(TCG-NA-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Pharaonic_Guardian_(TCG-NA-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Magician%27s_Force_(TCG-NA-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Dark_Crisis_(TCG-NA-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:The_Duelist_Genesis_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Crossroads_of_Chaos_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Crimson_Crisis_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Raging_Battle_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Ancient_Prophecy_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Stardust_Overdrive_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Absolute_Powerforce_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:The_Shining_Darkness_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Dark_Beginning_1_(TCG-EN-UE)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Dark_Revelation_Volume_1_(TCG-EN-UE)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Dark_Beginning_2_(TCG-EN-UE)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Dark_Revelation_Volume_2_(TCG-EN-UE)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Dark_Revelation_Volume_3_(TCG-EN-UE)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Dark_Revelation_Volume_4_(TCG-NA-UE)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Dark_Legends_(TCG-NA-UE)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:The_Lost_Millennium_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Cybernetic_Revolution_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Elemental_Energy_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Shadow_of_Infinity_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Enemy_of_Justice_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Generation_Force_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Photon_Shockwave_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Order_of_Chaos_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Galactic_Overlord_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Return_of_the_Duelist_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Abyss_Rising_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Cosmo_Blazer_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Lord_of_the_Tachyon_Galaxy_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Judgment_of_the_Light_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Shadow_Specters_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Legacy_of_the_Valiant_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Primal_Origin_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Duelist_Alliance_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:The_New_Challengers_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Secrets_of_Eternity_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Crossed_Souls_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Clash_of_Rebellions_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Dimension_of_Chaos_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Breakers_of_Shadow_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Shining_Victories_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Power_of_the_Duelist_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Cyberdark_Impact_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Strike_of_Neos_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Force_of_the_Breaker_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Tactical_Evolution_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Duelist_Revolution_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Starstrike_Blast_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Storm_of_Ragnarok_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Extreme_Victory_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Gladiator%27s_Assault_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Phantom_Darkness_(TCG-EN-1E)',
    'http://yugioh.wikia.com/wiki/Set_Card_Galleries:Light_of_Destruction_(TCG-EN-1E)' ]

console.log('start')
    getCardLinks = function (count, urls){
        console.log('Im the', + count + 'iteration');
        request(`${urls[count]}`, function(err, resp, body){
        if(!err && resp.statusCode == 200){
          var $ = cheerio.load(body)
          // Pull Card Link
          $('a:nth-child(4)', `#gallery-${count}`).each(function(){
            console.log('reuqest', count)

            var link = (`http://yugioh.wikia.com${this.attribs.href}`)
            cardLinks.push(link)
            console.log(cardLinks)
            console.log(cardLinks.length)
            })
          }
        })
      }
for (var count = 0; count <= urls.length; count++) {
  getCardLinks(count, urls)
}
